GET http://localhost:4000/

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "name": "admin",
  "password": "12345"
}

###
POST http://localhost:4000/users
Content-Type: application/json

{
   "name":"admin",
    "description":"hallo ich bin der admin",
    "password":"12345",
    "email":"admin@email.com"
}


###

GET http://localhost:4000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzExNzIzNTA5LCJleHAiOjE3MTE3MjM1MjR9.6O-CkL4uzsB3q-E3bxTkWSZDxk40wwX684DDqGG9Y0Y

###
POST http://localhost:4000/friendships
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MTY5MDg2NzIsImV4cCI6MTcxNjkxMjI3Mn0.80t-Fu2Ky1zUHXICNIHcXdQOpte9CmLHbm___h-ATD4
Content-Type: application/json

{
  "user_id": 10,
  "friend_id": 6
}

###
GET http://localhost:4000/friendships
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MTY5MDg2NzIsImV4cCI6MTcxNjkxMjI3Mn0.80t-Fu2Ky1zUHXICNIHcXdQOpte9CmLHbm___h-ATD4
Content-Type: application/json

{
  "user_id": 2
}

###
GET http://localhost:4000/user/5
Content-Type: application/json




###
